### PR TITLE
WIP: Update to 2.0.1

### PR DESCRIPTION
**Pull request by TheGreatMcPain**
It merged cleanly, but I still have to see if it actually runs.

### CODE REVIEW

**Comment by TheGreatMcPain** [comment]
It launches, but it gets stuck at "Waiting for Among Us" when it sees that the
game is running.

**Comment by pilot51** [comment]
Aside from the "Waiting for Among Us" issue, the overlay appears to be broken and covering up the entire Among Us screen with black, even when overlay is set to hidden. I removed the overlay code from main/index.ts and that resolved it.

**Comment by TheGreatMcPain** [comment]
I found that merging the commit [Merge branch 'feature/x64'](https://github.com/ottomated/CrewLink/commit/c2cfd74cd9894778c946de303c9473d6c5785776) is causing the "Waiting for Among Us" issue.

**Comment by TheGreatMcPain** [comment]
Looks like the `findPattern` function needs to be implemented in @zbanks' `memoryjs` fork since it's being used in `main/GameReader.ts` now.

**Comment by ghaith** [comment]
findPattern's original implementation should work directly since the Module Struct has the required information now. I didn't get a chance to work on it yet though just took a quick look.
https://github.com/Rob--/memoryjs/blob/bfde6ca9ac9c408bd25826a66429e84b94552d12/lib/pattern.cc

Update: I spoke too soon, needs more work.
Best bet  right now is to revert the x64 commit i assume?

**Comment by TheGreatMcPain** [comment]
I started working on a [pull-request](https://github.com/zbanks/memoryjs/pull/2)

I think I've gotten the `pattern.cc/h` files ported over and I just need to get it implemented in `memoryjs.cc/h`.

**Comment by TheGreatMcPain** [comment]
I've gotten the findPattern function implemented (not sure if it works yet), but I still have no idea where the
"Waiting for Among Us" error is coming from.

**Comment by ghaith** [comment]
> I've gotten the findPattern function implemented (not sure if it works yet), but I still have no idea where the
> "Waiting for Among Us" error is coming from.

The GameReader.ts code now uses the module.handle in several places, we have to pass process IDs to all of these i assume, did you try that? I might be able to also take a look in the afternoon (It's ~7 where I live).

**Comment by TheGreatMcPain** [comment]
According to `memoryjs.cc` in the memoryjs fork, the process ID already gets passed to both `module.th32ProcessID` and `module.handle`.

**Comment by ghaith** [comment]
I got a bit further with debugging this, now i get the game to crash on start =)
In your memoryjs fix, you are missing the function definition for node:
`exports.Set(Napi::String::New(env, "findPattern"), Napi::Function::New(env, findPattern));` in the init() function of memoryjs.cc

To debug, i am using vscode, which shows me a debug button on the scrips section of the package.json in CrewLink where i chose to debug the dev script. Then i can place breakpoints in ts files. I did not yet get it to go into cpp code, or print anything from the cpp code to the console. Maybe you have better luck than me I will also try again tomorrow.

**Comment by TheGreatMcPain** [comment]
> I got a bit further with debugging this, now i get the game to crash on start =)
> In your memoryjs fix, you are missing the function definition for node:
> `exports.Set(Napi::String::New(env, "findPattern"), Napi::Function::New(env, findPattern));` in the init() function of memoryjs.cc
> 
> To debug, i am using vscode, which shows me a debug button on the scrips section of the package.json in CrewLink where i chose to debug the dev script. Then i can place breakpoints in ts files. I did not yet get it to go into cpp code, or print anything from the cpp code to the console. Maybe you have better luck than me I will also try again tomorrow.

Right, I forgot to do that. Oops.

**Comment by TheGreatMcPain** [comment]
I've added the `exports.Set()` line to `memoryjs.cc`. CrewLink exits
instantly when Among Us is running, so something must be wrong with my CPP code.

**Comment by Freso** [comment]
FWIW, [2.0.1 was released](https://github.com/ottomated/CrewLink/releases/tag/v2.0.1), so it may be desirable to rebase this PR on/to that.

**Comment by TheGreatMcPain** [comment]
Yup, I was planning on doing that once we get `findPattern` working in memoryjs.

**Comment by TheGreatMcPain** [comment]
So, out of curiousity I pulled-in the changes for version 2.0.1 and tried it
out to find that it was finally able to reach the `MENU` window.

Unfortunately it doesn't go passed that though.

**Comment by ghaith** [comment]
Using your latest memoryjs branch I am able to get into the lobby didn't test beyond that yet
i don't currently have your branch of Crewlink checked out, but a merge I did from 2.0.1, should not be different though.

**Comment by TheGreatMcPain** [comment]
Yup, just got it working earlier. Haven't tested a game with it yet.

I've already merged 2.0.1 which fixed a crash on start that 2.0.0 had.

Not sure what to do with the overlay.

**Comment by ghaith** [comment]
Good to hear, the overlay is broken on my side too, was not sure if it's my desktop env since i'm on i3, but i was able to close it and just get into the game normally

**Comment by TheGreatMcPain** [comment]
Same, I was thinking about doing what @pilot51 suggested and just hardcode it out for now.

**Comment by papodaca** [comment]
Playing around with the overlay code, I am not convinced that it uses the memoryjs functionality. What is happening, that I don't quite understand fully, the overlay window isn't being made transparent weather by window managers or something, I tried many times to set all web elements transparent in the inspector. No Dice.

Here is a small patch to disable it.
```patch
diff --git a/src/main/index.ts b/src/main/index.ts
index c3c9be6..ed3d595 100644
--- a/src/main/index.ts
+++ b/src/main/index.ts
@@ -124,7 +124,7 @@ function createOverlay() {
 		);
 	}
 	window.setIgnoreMouseEvents(true);
-	electronOverlayWindow.attachTo(window, 'Among Us');
+	// electronOverlayWindow.attachTo(window, 'Among Us');
 
 	if (isDevelopment) {
 		// Force devtools into detached mode otherwise they are unusable
```

**Comment by TheGreatMcPain** [comment]
@papodaca Does the overlay actually display anything besides a blank window?

**Comment by TheGreatMcPain** [comment]
Looks like the library they're using to create the overlay supports Linux.

The repository for it is [here.](https://github.com/SnosMe/electron-overlay-window)

**Comment by papodaca** [comment]
There is for sure something else broken with the overlay window. It doesn't seem that any of the react code starts doing anything really.

**Comment by TheGreatMcPain** [comment]
I tried the demo code that [electron-overlay-window](https://github.com/SnosMe/electron-overlay-window) provides, and I'm getting similar results.  When I have it attach to my file manager it renders the demo stuff on the overlay, but the overlay itself is not transparent.

I use bspwm for my window manager and picom for compositing.

**Comment by papodaca** [comment]
So lots of playing with that demo, and it seems like this feature of electron is just super [buggy](https://github.com/electron/electron/issues/25153). There are many bugs reports about transparent windows for Windows and linux, kind of annoying.

So at least for me, I have been able to get the demo code to work with 9.4.1.

**Comment by TheGreatMcPain** [comment]
I was able to get the demo working by disabling hardware acceleration as suggested [here.](https://github.com/electron/electron/issues/25153#issuecomment-754632811)

**Comment by papodaca** [comment]
Unfortunately that doesn't seem to help in the case of CrewLink

**Comment by TheGreatMcPain** [comment]
Looks like we also need to add a delay like the demo code does.

**Comment by TheGreatMcPain** [comment]
Oops

**Comment by TheGreatMcPain** [comment]
The overlay should be transparent now, but I'm not sure how to get the rest of the overlay working.

**Comment by papodaca** [comment]
Ok so I guess I don't really know if the overly is broken or not, now that it is transparent. The overlay as designed does not display anything until a game is started. I have verified that the react code does get launched via the web console in dev mode.

**Comment by ghaith** [comment]
For me the overlay does not let me click anything in the game so I am disabling it

**Comment by papodaca** [comment]
maybe its possible to add a CLI flag to disable it? Its possible there are just some window managers this will never work on.

Edit: Lets not forget about wayland, I have no clue if it could work on that.

**Comment by TheGreatMcPain** [comment]
Based on the overlay library's [github repo](https://github.com/SnosMe/electron-overlay-window). I'd say Wayland is out of the question although it might work via XWayland. (I'm not familiar with Wayland since I have an Nvidia card.)

I'll look into adding a cmdline option to hard disable the overlay since the `hidden` overlay setting in CrewLink doesn't completely disable it.

**Comment by MimzyFang** [comment]
I just tried it out, the overlay is misaligned but that's the only Issue I found.
I use Manjaro KDE Plasma

**Comment by TheGreatMcPain** [comment]
I ran into that with bspwm, but the overlay itself doesn't stay on top for me.

@Fauli1221 Does it actually display anything for you?

Also, messing with the electron-overlay-window demo code I noticed that the
overlay will only properly work on bspwm if the window is in tiling mode.

**Comment by Phundrak** [comment]
I just tested under Awesome (latest commit from this PR, the kernel Arch Linux with Linux 5.10.8-zen1-1-zen), the overlay is created in another window I can manually align with Among Us, but it also prevents me from clicking anything.

**Comment by pilot51** [comment]
Is detection working properly for anyone? The lack of talk about it is starting to make me wonder. I still can't get it working on Mint 20 with the latest commit. Overlay is honestly the least of my concerns.

**Comment by TheGreatMcPain** [comment]
@pilot51 I haven't had any issues getting CrewLink to detect the game ever since I got memoryjs's `findPattern()` function working.  I can even create a game in which CrewLink will react accordingly.  I haven't actually tried it in a real game yet though.

Are you running CrewLink after Among Us has started?

**Comment by pilot51** [comment]
Nevermind, my mistake. I'm using a script that automatically sets ptrace before and after running CrewLink and I forgot to update it from 2.0.0 to 2.0.1. It's working now.

**Comment by mjeveritt** [comment]
@TheGreatMcPain hey, I see you're another Gentoo 'nerd' :smile:  - can we have a chat about CrewLink issues on IRC some time? I am kinda interested to see if we can also port Bettercrewlink over to Linux also.

I'm having some epic audio issues, not sure what is going on.

Weirdly, it seems like I have a working overlay on KDE/Kubuntu ... (!).

Have set up yarn here, but it sucks CPU something silly (possibly also the reason why audio stutters like a b1tch ..

**Comment by TheGreatMcPain** [comment]
@mjeveritt Sure, but I'm not too familiar with IRC (I only used it to access xbins(dot)org to get OG Xbox homebrew software).

I'd imagine getting BetterCrewLink working on Linux shouldn't be too difficult since it doesn't require any extra `memoryjs` functionality. EDIT: Based on previous commits on this repository this shouldn't be too difficult.

I did have some "robo" voice issues when used 1.2.1 with some friends before 2.0.0 came out.  It seems like it was happening on their end too, so it's not entirely a Linux specific issue.

**Comment by mjeveritt** [comment]
> @mjeveritt Sure, but I'm not too familiar with IRC (I only used it to access xbins(dot)org to get OG Xbox homebrew software).

There's a webchat for Freenode, or other clients from (he)xchat, irrsi etc. Reason I mention it is a lot of Gentoo dev does also go on there too! My nick is 'kveremitz' over there.

> I did have some "robo" voice issues when used 1.2.1 with some friends before 2.0.0 came out. It seems like it was happening on their end too, so it's not entirely a Linux specific issue.

Yeah we tried a couple of different servers, but the problem definitely prevailed. Looking in htop there was a process in /proc/sys/exe or such hogging CPU which doesn't sound right. It definitely seemed like some resource bottleneck.
I am playing public beta, but not sure that makes a difference? (still 2020.12.9s iirc).

**Comment by nathanielwarner** [comment]
It's working for me! There was some glitches, but no more than for my Windows-using friends. Thanks for the work you've put into this @TheGreatMcPain and @zbanks

**Comment by TheGreatMcPain** [comment]
I have recently implemented `getProcesses` in my fork of `memoryjs` which allows `CrewLink` to properly detect if `Among Us` is running or not.

This means `CrewLink` can now be launched before starting `Among Us` and should continue to work even if the game closes/restarts.

**Comment by TheGreatMcPain** [comment]
Had to close, because github won't let me change the pull-request branch.

Continued in #18.

**Pull request closed without merging**
