### PR TITLE
Crewlink 1.2.0 Support

### LINKED ISSUE #4: CrewLink v1.2.0
CrewLink has updated to v1.2.0 and I think this has broken compatibility between the official server and this fork. When I join a lobby, the green circle showing I'm speaking is red instead, even on my CrewLink instance. Is there any way to fix this on my end, or should I just wait for this fork to update?

### PR DESCRIPTION
**Pull request by ghaith**
Updated the repo for 1.2.0
Added the uiohook from my system as the original is broken.
Fixes #4 #3

### CODE REVIEW

**Comment by M-Reimer** [comment]
I'm not in charge here, but after having a short look over your changes I wonder if you could provide source code for the uiohook.so you added. I feel a bit uncomfortable about just pulling random binaries on my system. Would really prefer being able to compile this one myself.

**Comment by ghaith** [comment]
Hello, I just installed this aur package and pulled it from there https://aur.archlinux.org/packages/libuiohook/

Keep in mind it could be just broken on arch linux, if you are on ubuntu try doing yarn install and then yarn run dist-linux and you get the AppImage with the original dependencies.

**Comment by Denton-L** [comment]
I just tested it and it seems to be working. I'm sure there are a few things we want to clean up before merging (such as the Building from source instructions) but thanks for getting it working!

**Comment by Denton-L** [comment]
I seem to be getting the following error when I run this:

`pkg/crewlink-testing/opt/CrewLink/crewlink: symbol lookup error: /storage/denton/aur/crewlink/pkg/crewlink-testing/opt/CrewLink/resources/app.asar.unpacked/node_modules/iohook/builds/electron-v80-linux-x64/build/Release/uiohook.so: undefined symbol: xkb_x11_get_core_keyboard_device_id`

**Comment by M-Reimer** [comment]
I guess the uihook.so should not be replaced after all. The existing builds seem to match for Ubuntu and other distributions should build their own version which matches their environment.

**Comment by ghaith** [comment]
> I guess the uihook.so should not be replaced after all. The existing builds seem to match for Ubuntu and other distributions should build their own version which matches their environment.

Yes makes sense, I'll fix that so we don't have an extra binary, and I'll add this to the release I have on my branch with an "arch Linux" target.

**Comment by ghaith** [comment]
> I seem to be getting the following error when I run this:
> 
> `pkg/crewlink-testing/opt/CrewLink/crewlink: symbol lookup error: /storage/denton/aur/crewlink/pkg/crewlink-testing/opt/CrewLink/resources/app.asar.unpacked/node_modules/iohook/builds/electron-v80-linux-x64/build/Release/uiohook.so: undefined symbol: xkb_x11_get_core_keyboard_device_id`

On what distro are you running? This was the issue I had on Arch Linux and I copied the uiohook.so from an AUR package to solve it. You can find that binary in the iohook folder and replace the uiohook.so file you see in the error message with that one then run it again

**Comment by Denton-L** [comment]
I'm on Arch as well. I may have mistakenly copied it into the wrong location, though. I'll check again tomorrow.

**Comment by ghaith** [comment]
I tried building iohook from source again, and i still have the same issue, but interestingly enough, if i compile the libuiohook contained inside the iohook package and copy that it works, so if anyone wants to build from source that might be the best solution so far.

**Comment by zbanks** [comment]
Thanks @ghaith for putting this together. 

I'm trying to figure out how to properly work around `iohook`'s build issues:

I admittedly did a bad thing on my last release -- I patched `iohook`, build it locally, then checked in those built files, copying what was being done for the Windows side. I've just now opened up [PR 279 on iohook](https://github.com/wilix-team/iohook/pull/279) to fix their prebuilds for Linux. 

If that PR can get merged relatively soon, that should resolve iohook build complexity.

(Note to self: after a iohook strategy is chosen, make sure the [Building from Source](https://github.com/zbanks/CrewLink/blob/master/README.md#building-from-source) section of the readme is up-to-date)

**Comment by ghaith** [comment]
@zbanks, 1.2.1 can be merged without issue on this PR, should I do it or would you prefer a new PR?
~I also have a (hacky) fix for #7 which could be pushed here by allowing the game to be started from CrewLink, or we can wait until it's merged~ Edit: I just noticed that fix segfaults after the last update

**Comment by zbanks** [comment]
~~Let's do another PR for 1.2.1.~~ Edit: It looks like 1.2.1 merges cleanly, I'll merge it in today. Edit 2: [done](https://github.com/zbanks/CrewLink/releases/tag/v1.2.1)!

After this PR merges in, I'm going to point the `iohook` dependency to [my branch that is in PR](https://github.com/zbanks/iohook/tree/268/add-xkbcommon-lflags) to fix that .so/undefined symbol problem. (I've uploaded prebuilts from that PR into my fork)

```diff
diff --git a/package.json b/package.json
index 1114306..80cc578 100644
--- a/package.json
+++ b/package.json
@@ -49,7 +49,7 @@
     "electron-store": "^6.0.1",
     "electron-updater": "^4.3.5",
     "electron-window-state": "^5.0.3",
-    "iohook": "^0.7.2",
+    "iohook": "git://github.com/zbanks/iohook.git#0.7.2_zbanks",
     "memoryjs": "https://github.com/zbanks/memoryjs.git",
     "pretty-bytes": "^5.5.0",
     "react": "^17.0.1",
```

**Review by zbanks — APPROVED** [review]

**Pull request merged**
